#############################################################################
# Makefile for building: pour_tudor.app/Contents/MacOS/pour_tudor
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  pour_tudor.pro
# Template: app
# Command: /Users/tudoroancea/Applications/Qt/5.14.2/clang_64/bin/qmake -o Makefile pour_tudor.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang -F/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib
QMAKE         = /Users/tudoroancea/Applications/Qt/5.14.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/tudoroancea/Applications/Qt/5.14.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/tudoroancea/Applications/Qt/5.14.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pour_tudor1.0.0
DISTDIR = /Users/tudoroancea/Documents/GitHub/game_of_life/.tmp/pour_tudor1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cell.cpp \
		cell_.cpp \
		motifs.cpp \
		game_of_life.cpp \
		main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = cell.o \
		cell_.o \
		motifs.o \
		game_of_life.o \
		main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/lex.prf \
		pour_tudor.pro cell.h \
		cell_.h \
		motifs.h \
		game_of_life.h \
		mainwindow.h cell.cpp \
		cell_.cpp \
		motifs.cpp \
		game_of_life.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = pour_tudor
DESTDIR       = 
TARGET        = pour_tudor.app/Contents/MacOS/pour_tudor

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/tudoroancea/Documents/GitHub/game_of_life/pour_tudor.pro


include /Users/tudoroancea/Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

pour_tudor.app/Contents/MacOS/pour_tudor:  $(OBJECTS)  
	@test -d pour_tudor.app/Contents/MacOS/ || mkdir -p pour_tudor.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pour_tudor.pro ../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/lex.prf \
		pour_tudor.pro \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile pour_tudor.pro
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/qdevice.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/device_config.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/unix.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/mac.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/macx.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/qconfig.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/default_post.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qt.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/resources.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/moc.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/uic.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/yacc.prf:
../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/lex.prf:
pour_tudor.pro:
../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pour_tudor.pro

qmake_all: FORCE

pour_tudor.app/Contents/PkgInfo: 
	@test -d pour_tudor.app/Contents || mkdir -p pour_tudor.app/Contents
	@$(DEL_FILE) pour_tudor.app/Contents/PkgInfo
	@echo "APPL????" > pour_tudor.app/Contents/PkgInfo
pour_tudor.app/Contents/Resources/empty.lproj: 
	@test -d pour_tudor.app/Contents/Resources || mkdir -p pour_tudor.app/Contents/Resources
	@touch pour_tudor.app/Contents/Resources/empty.lproj
	
pour_tudor.app/Contents/Info.plist: 
	@test -d pour_tudor.app/Contents || mkdir -p pour_tudor.app/Contents
	@$(DEL_FILE) pour_tudor.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,TestXCode.pour-tudor,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},TestXCode.pour-tudor,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,pour_tudor,g" -e "s,@LIBRARY@,pour_tudor,g" -e "s,\$${EXECUTABLE_NAME},pour_tudor,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang/Info.plist.app >pour_tudor.app/Contents/Info.plist

all: Makefile \
		pour_tudor.app/Contents/PkgInfo \
		pour_tudor.app/Contents/Resources/empty.lproj \
		pour_tudor.app/Contents/Info.plist pour_tudor.app/Contents/MacOS/pour_tudor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cell.h cell_.h motifs.h game_of_life.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents cell.cpp cell_.cpp motifs.cpp game_of_life.cpp main.cpp mainwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r pour_tudor.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Applications/Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		cell.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		cell_.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/Qt \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		game_of_life.h \
		motifs.h \
		moc_predefs.h \
		../../../Applications/Qt/5.14.2/clang_64/bin/moc
	/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/tudoroancea/Documents/GitHub/game_of_life/moc_predefs.h -I/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/mkspecs/macx-clang -I/Users/tudoroancea/Documents/GitHub/game_of_life -I/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/tudoroancea/Applications/Qt/5.14.2/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

cell.o: cell.cpp cell.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o cell.cpp

cell_.o: cell_.cpp cell_.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/Qt \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qrect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell_.o cell_.cpp

motifs.o: motifs.cpp motifs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o motifs.o motifs.cpp

game_of_life.o: game_of_life.cpp game_of_life.h \
		motifs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_of_life.o game_of_life.cpp

main.o: main.cpp mainwindow.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		cell.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		cell_.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/Qt \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		game_of_life.h \
		motifs.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		cell.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		cell_.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/Qt \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../Applications/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		game_of_life.h \
		motifs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/pour_tudor/bin || mkdir -p $(INSTALL_ROOT)/opt/pour_tudor/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/pour_tudor/bin/pour_tudor.app
	
	$(QINSTALL) pour_tudor.app $(INSTALL_ROOT)/opt/pour_tudor/bin/pour_tudor.app
	-$(STRIP) $(INSTALL_ROOT)/opt/pour_tudor/bin/pour_tudor.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/pour_tudor/bin/pour_tudor.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/pour_tudor/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

